@echo off
echo Starting ReconApp...
echo Installing dependencies (this might take a moment if not installed)...
python -m pip install -r requirements.txt
echo.
echo Starting Server...
echo Opening browser...
start http://127.0.0.1:8000
python -m uvicorn main:app --reload
pause
